services:
  app:
    build: .
    container_name: gestao_residuos_app
    ports:
      - "3001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - gestao_net

networks:
  gestao_net:
    driver: bridge
