// <auto-generated />
using System;
using AppGestaoDeResiduos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AppGestaoDeResiduos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202232844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Caminhao", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("caminhao_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaminhaoId"));

                    b.Property<int?>("LocalizacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("localizacao_id");

                    b.Property<string>("Placa")
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)")
                        .HasColumnName("placa");

                    b.Property<int?>("QtdDeColetas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qtd_de_coletas");

                    b.Property<int?>("QtdDeColetasMax")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qtd_de_coletas_max");

                    b.HasKey("CaminhaoId");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("tb_caminhao");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Coleta", b =>
                {
                    b.Property<int>("ColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("coleta_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColetaId"));

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("caminhao_id");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_coleta");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("endereco_id");

                    b.Property<int?>("QtdDeColeta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qtd_de_coletas");

                    b.HasKey("ColetaId");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("tb_coleta");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("endereco_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoId"));

                    b.Property<int?>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("estado");

                    b.Property<int?>("Numero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("rua");

                    b.HasKey("EnderecoId");

                    b.ToTable("tb_endereco");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tb_localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizacaoId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora");

                    b.Property<int?>("Latitude")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("latitude");

                    b.Property<int?>("Longitude")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("longitude");

                    b.HasKey("LocalizacaoId");

                    b.ToTable("tb_localizacao");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Notificacao", b =>
                {
                    b.Property<int?>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("notificacao_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("NotificacaoId"));

                    b.Property<string>("Mensagem")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("mensagem");

                    b.HasKey("NotificacaoId");

                    b.ToTable("tb_notificacao");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool?>("AgendouColeta")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("agendou_coleta");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("endereco_id");

                    b.Property<bool?>("FoiNotificado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("foi_notificado");

                    b.Property<string>("Nome")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("nome");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.UsuarioColeta", b =>
                {
                    b.Property<int>("UsuarioColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_coleta_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioColetaId"));

                    b.Property<int>("ColetaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("coleta_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioColetaId");

                    b.HasIndex("ColetaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_usuario_coleta");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.UsuarioNotificacao", b =>
                {
                    b.Property<int>("UsuarioNotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_notificacao_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioNotificacaoId"));

                    b.Property<DateTime>("DataNotificacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_notificacao");

                    b.Property<int>("NotificacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("notificacao_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.HasKey("UsuarioNotificacaoId");

                    b.HasIndex("NotificacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_usuario_notificacao");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Caminhao", b =>
                {
                    b.HasOne("AppGestaoDeResiduos.Models.Localizacao", "Localizacao")
                        .WithMany("Caminhoes")
                        .HasForeignKey("LocalizacaoId");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Coleta", b =>
                {
                    b.HasOne("AppGestaoDeResiduos.Models.Caminhao", "Caminhao")
                        .WithMany("Coletas")
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGestaoDeResiduos.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Caminhao");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Usuario", b =>
                {
                    b.HasOne("AppGestaoDeResiduos.Models.Endereco", "Endereco")
                        .WithMany("Usuarios")
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.UsuarioColeta", b =>
                {
                    b.HasOne("AppGestaoDeResiduos.Models.Coleta", "Coleta")
                        .WithMany("UsuarioColetas")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGestaoDeResiduos.Models.Usuario", "Usuario")
                        .WithMany("UsuarioColetas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.UsuarioNotificacao", b =>
                {
                    b.HasOne("AppGestaoDeResiduos.Models.Notificacao", "Notificacao")
                        .WithMany("UsuarioNotificacoes")
                        .HasForeignKey("NotificacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppGestaoDeResiduos.Models.Usuario", "Usuario")
                        .WithMany("UsuarioNotificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Caminhao", b =>
                {
                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Coleta", b =>
                {
                    b.Navigation("UsuarioColetas");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Endereco", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Localizacao", b =>
                {
                    b.Navigation("Caminhoes");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Notificacao", b =>
                {
                    b.Navigation("UsuarioNotificacoes");
                });

            modelBuilder.Entity("AppGestaoDeResiduos.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioColetas");

                    b.Navigation("UsuarioNotificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
