name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Gatilho para a execução do pipeline quando houver push para a branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Ou a versão do runner que você está utilizando

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install libssl dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0" # Ou a versão que você estiver utilizando

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging server..."
          # Comandos para deploy no ambiente de staging, ex: push para Docker Hub, deploy em servidor de staging

  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_staging

    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Comandos para deploy em produção
