name: Build and deploy container app to Azure Web App - AppGestaoDeResiduosStg

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore & Build
        run: |
          dotnet restore --force
          dotnet build --no-restore

      - name: Run Tests
        run: dotnet test AppGestaoDeResiduos/AppGestaoDeResiduos.csproj --no-build --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_4fa4c72245d640aab3828bdb0ba91ae3 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_4dd6fd06efd24b2b9977ddf5a328de77 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4fa4c72245d640aab3828bdb0ba91ae3 }}/appgestaoderesiduos-stg:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: AppGestaoDeResiduosStg
          slot-name: production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_62b704ef018346a2945bbb216fcae6d4 }}
          images: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b78c32bb41964e5689bf73cf9d8bfc7d }}/appgestaoderesiduos-stg:${{ github.sha }}
